# https://taskfile.dev

version: '2'

tasks:
  corpus_txt_to_json:
    silent: true
    sources:
      - resources/answer_exbrain.txt
      - resources/test_exbrain.txt
      - resources/training_corpus_exbrain.txt
    generates:
      - resources/training.json
      - resources/test.json
    cmds:
      - python ./scripts/python/make_json_corpus.py
  corpus_simple_pos:
    silent: true
    deps: ['corpus_txt_to_json']
    sources:
      - resources/training.json
      - resources/test.json
    generates:
      - resources/training_simple.json
      - resources/test_simple.json
    cmds:
      - python ./scripts/python/make_simple_pos.py
  corpus_del_data:
    silent: true
    deps: ['corpus_simple_pos']
    sources:
      - resources/training_simple.json
      - resources/test_simple.json
    generates:
      - resources/training_del_indices.tsv
      - resources/test_del_indices.tsv
    cmds:
      - python ./scripts/python/make_del_data.py
